# Generated by Django 3.2.18 on 2023-03-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_change', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_tem',
            old_name='AverageTemperature',
            new_name='averageTemperature',
        ),
        migrations.RenameField(
            model_name='global_tem',
            old_name='AverageTemperatureUncertainty',
            new_name='averageTemperatureUncertainty',
        ),
        migrations.RenameField(
            model_name='global_tem',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='global_tem',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='global_tem',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='country_id',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='global_tem',
            name='Country',
        ),
        migrations.AddField(
            model_name='country_id',
            name='country',
            field=models.TextField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='global_tem',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='global_tem', to='climate_change.country_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country_id',
            name='id',
            field=models.IntegerField(),
        ),
    ]
