# Generated by Django 4.1.7 on 2023-03-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_change', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Globaltem_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.TextField()),
                ('landAverageTemperature', models.FloatField()),
                ('landAverageTemperatureUncertainty', models.FloatField()),
                ('landMaxTemperature', models.FloatField()),
                ('landMaxTemperatureUncertainty', models.FloatField()),
                ('landMinTemperature', models.FloatField()),
                ('landMinTemperatureUncertainty', models.FloatField()),
                ('landAndOceanAverageTemperature', models.FloatField()),
                ('landAndOceanAverageTemperatureUncertainty', models.FloatField()),
            ],
        ),
    ]
