# Generated by Django 4.1.7 on 2023-03-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_change', '0002_alter_global_tem_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_tem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
